### ISSUE TITLE
ImportError: No module named 'PKITools.asn1formater.pyasn1'

### ISSUE THREAD

**Issue by lennybacon** [FlashSystems/PKITools#1]
When I place the directory ```PKITools``` into the path ```Data/Packages``` the console spits the following error:

```
reloading plugin PKITools.pkitools
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Program Files\Sublime Text 3\Data\Packages\PKITools\pkitools.py", line 2, in <module>
    from .asn1formater.pyasn1.codec.der import decoder, encoder
ImportError: No module named 'PKITools.asn1formater.pyasn1'
```
Any ideas?

**Comment by FlashSystems** [comment]
I'm sorry, but this plugin is currently incomplete and will not work. It was an experiment and I did not get around to finish it. Maybe some day...
